[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bgwarcompany"
authors = [{name = "Helene", email = "sillystring13@gmail"}]
dynamic = ["version", "description"]
